spring.application.name=vibehub

# DB configuration
Spring.datasource.url=jdbc:mysql://localhost:3306/vibehub?createDatabaseIfNotExist=true
Spring.datasource.Username = root
Spring.datasource.Password = Admin@123

# Granting DDL permissions to hibernate
Spring.jpa.hibernate.ddl-auto = update

# All the queries run by hibernate will be shown
Spring.jpa.hibernate.show-sql = true
