spring.application.name=vibehub

# DB configuration
Spring.datasource.url=jdbc:mysql://localhost:3306/vibehub?createDatabaseIfNotExist=true
Spring.datasource.Username = root
Spring.datasource.Password = Admin@123

Spring.jpa.hibernate.ddl-auto = update

Spring.jpa.hibernate.show-sql = true
